version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_demo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  anvil:
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      ANVIL_IP_ADDR: 0.0.0.0
    command: ["anvil", "--host", "0.0.0.0", "--block-time", "0"]
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/8545 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
